nelmio_api_doc:
    documentation:
        info:
            title: Drop obServer
            description: This is an awesome app!
            version: 0.1.0 BETA
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
